# Generated by Django 4.1.7 on 2023-03-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0004_alter_meep_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
