# Generated by Django 4.1.7 on 2023-03-24 22:22

from django.db import migrations, models
import musker.models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0007_alter_comment_meep_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='meep_image_url',
            field=models.ImageField(blank=True, null=True, upload_to=musker.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image_url',
            field=models.ImageField(blank=True, null=True, upload_to=musker.models.get_image_path),
        ),
    ]
