# Generated by Django 4.1.7 on 2023-03-26 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musker', '0008_meep_meep_image_url_alter_profile_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_meeps', to=settings.AUTH_USER_MODEL),
        ),
    ]
